apiVersion: batch/v1
kind: CronJob
metadata:
  name: avro-parquet-compactor
  namespace: datalake
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: compactor
        spec:
          containers:
          - name: compactor
            image: razvan1y/compactor:latest
            imagePullPolicy: Always
            env:
              - name: STORAGE_ROOT
                value: "/data"
              - name: SCHEMA_API_URL
                value: "http://metadata-service.datalake.svc.cluster.local:8080"
            volumeMounts:
              - name: dfs-storage
                mountPath: /data
          restartPolicy: OnFailure
          volumes:
            - name: dfs-storage
              persistentVolumeClaim:
                claimName: global-data-pvc