apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-consumer
  namespace: datalake
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ingestion-consumer
  template:
    metadata:
      labels:
        app: ingestion-consumer
    spec:
      containers:
        - name: ingestion-consumer
          image: razvan1y/ingestion-consumer:latest
          imagePullPolicy: Always
          env:
            - name: KAFKA_BROKERS
              value: "kafka-0.kafka-headless.kafka.svc.cluster.local:9092,kafka-1.kafka-headless.kafka.svc.cluster.local:9092,kafka-2.kafka-headless.kafka.svc.cluster.local:9092"
            - name: KAFKA_TOPIC
              value: "raw_test1"
            - name: KAFKA_GROUP_ID
              value: "ingestion-consumers"
            - name: SCHEMA_REGISTRY_HOST
              value: "schema-registry.default.svc.cluster.local"
            - name: SCHEMA_REGISTRY_PORT
              value: "8081"
            - name: MASTER_SERVICE_PORT
              value: "50055"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "250m"
