apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-consumer
  namespace: datalake
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ingestion-consumer
  template:
    metadata:
      labels:
        app: ingestion-consumer
    spec:
      containers:
        - name: ingestion-consumer
          image: razvan1y/ingestion-consumer:latest
          imagePullPolicy: Always
          env:
            - name: KAFKA_BROKERS
              value: "my-kafka-cluster-kafka-plain-bootstrap.kafka.svc.cluster.local:9092"
            
            - name: KAFKA_TOPIC_REGEX
              value: ".*"

            - name: KAFKA_GROUP_ID
              value: "ingestion-consumers-group"
              
            - name: KAFKA_DLT_TOPIC
              value: "ingestion-dlt"

            - name: SCHEMA_REGISTRY_HOST
              value: "metadata-service.datalake.svc.cluster.local:8081"
            - name: MASTER_ADDRESS
              value: "master.datalake.svc.cluster.local:50055"
            - name: OTEL_COLLECTOR_ADDR
              value: "otel-collector.observability.svc.cluster.local:4317"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"