apiVersion: v1
kind: Service
metadata:
  name: query-service
  namespace: datalake
  labels:
    app.kubernetes.io/name: query-service
spec:
  selector:
    app.kubernetes.io/name: query-service
  ports:
    - name: http
      port: 8086
      targetPort: 8086
    - name: https
      port: 443
      targetPort: 8443
    - name: grpc
      port: 50051
      targetPort: 50051
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-service
  namespace: datalake
  labels:
    app.kubernetes.io/name: query-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: query-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: query-service
    spec:
      containers:
        - name: query-service
          image: razvan1y/query-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8086
            - containerPort: 8443
            - containerPort: 50051
          env:
            - name: MASTER_SERVICE_ADDRESS
              value: master:50055
            - name: WORKER_SERVICE_ADDRESSES
              value: "worker-1:50051,worker-2:50051,worker-3:50051"
