apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: disable-mtls-identity-postgres
  namespace: datalake
spec:
  host: identity-postgres.datalake.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE # <--- Forces plain text (no mTLS)
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: disable-mtls-metadata-postgres
  namespace: datalake
spec:
  host: metadata-postgres.datalake.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
