apiVersion: v1
kind: ServiceAccount
metadata:
  name: metadata-service-sa
  namespace: datalake
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kafka
  name: kafka-topic-creator
rules:
- apiGroups: ["kafka.strimzi.io"]
  resources: ["kafkatopics"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metadata-service-bind
  namespace: kafka
subjects:
- kind: ServiceAccount
  name: metadata-service-sa
  namespace: datalake
roleRef:
  kind: Role
  name: kafka-topic-creator
  apiGroup: rbac.authorization.k8s.io